#!/bin/bash
#
# Copyright (c) 2015, Intel Corporation
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

OUTDIR=$1
SAMPLING_INTERVAL=$2
CMD=$3

COMMAND=java
OUTPUT_FILE=$OUTDIR/$COMMAND-stat

function run()
{
	#
	# pidstat parameters & header/fields tested with sysstat version 10.0.3
	#

	# Used pidstat parameters
	# -r = page faults & memory utilization
	# -u = CPU utilization
	# -d = I/O statistics
	# -h = display everything on a single line
	# -p ALL = show everything including inactive tasks
	#          (otherwise it will not show if no activity is performed)
	# -C cmd = command to be monitored

	# Header
	# Adjust pidstat header to include HostName and TimeStamp
	pidstat -rudh -p ALL -C init | awk -v host=$(hostname) '(/Time/){$1=$2=""; print "HostName","TimeStamp", $0}; fflush()' > $OUTPUT_FILE

	# Data
	pidstat -rudh -p ALL -C $COMMAND $SAMPLING_INTERVAL | awk -v cmd=$COMMAND -v host=$(hostname) '(!/^$/ && !/Time/ && !/CPU/){if ($NF == cmd){now=strftime("%s"); $1=""; print host, now, $0}; fflush()}' >> $OUTPUT_FILE &
}

case $CMD in
	"run") run ;;
	"post-process") ;;
esac
