#!/bin/bash
#
# Copyright (c) 2015, Intel Corporation
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

OUTDIR=$1
SAMPLING_INTERVAL=$2
CMD=$3

source instruments/_common.sh

function run()
{
	# SAR_VER is exported in the environment
	sar_impl=1
	ver_ge $SAR_VER 10.0.3 && sar_impl=2 # use 2nd implementation for sar version >= 10.0.3
	# for the future (change "11.0.1" below with the new tested version of sar)
	#ver_ge $sar_ver 11.0.1 && sar_impl=3

	case $sar_impl in
		2)
		/usr/bin/sar -n DEV $SAMPLING_INTERVAL | awk -v host=$(hostname) '(!/^$/ && !/Linux/){now=strftime("%s "); $1=""; if(/IFACE/){print "HostName","TimeStamp", $0} else {print host,now $0}}; fflush()' > $OUTDIR/netstat &
		;;

		*) # sar_impl == 1
		/usr/bin/sar -n DEV $SAMPLING_INTERVAL | awk -v host=$(hostname) '(!/^$/){if($0 &&!/Linux/){$1=""; $2=""; now=strftime("%s "); if(/IFACE/){print "HostName","TimeStamp", $0} else {print host,now $0}}}; fflush()' > $OUTDIR/netstat &
		;;
	esac
}

case $CMD in
	"run") run ;;
	"post-process") ;;
esac
