#!/bin/bash
#
# Copyright (c) 2014-2015, Intel Corporation
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


source ./common.sh

if [ -z "$ALL_NODES" ]; then
	echo "*** Please Specify at least one worker node in the config file ***"
	exit
fi


JOBID=$1

OUTDIR=$(pwd)/mst_tmp
rm -rf $OUTDIR
mkdir $OUTDIR
mkdir $OUTDIR/jobhistory
if $GC ; then
	mkdir $OUTDIR/gc_summary
fi
mkdir $OUTDIR/instruments
mkdir $OUTDIR/conf
cp $MASTER_SCRIPT_DIR/result_template*.xlsm $OUTDIR/instruments

function on_exit()
{
echo "Exiting Script ..." 
$MASTER_SCRIPT_DIR/killjob
killall -e killjvms
rm -rf mst_tmp  
}

getJobid(){
if [ -z "$JOBID" ]; then
	JOBID=$(date +%s)
fi

echo JOBID is $JOBID
}

#Gather the data
#instruments

get_instruments(){
for i in $ALL_NODES; do
	node=$(echo $i | cut -f1 -d:)
	mkdir $OUTDIR/instruments/$node
	scp_from_w $i "$WORKER_TMP_DIR/*" $OUTDIR/instruments/$node 1> /dev/null &
done
wait

}

#Gather conf files
get_conf(){
for i in $CONF_DIRS
do
	node=${i%%/*} # remove path from the end of the CONF_DIR (format: hostname:[path])
	path=/${i#*/} # remove everything before the first slash
	host=$(echo $node | cut -d: -f1)
	if [ $node == $host ]; then
		# No remote path provided (missing ":"), local configuration dir ($node) to be copied
		cp -a $node $OUTDIR/conf 1> /dev/null &
	else
		if [ ! -d "$OUTDIR/conf/$node" ]; then mkdir $OUTDIR/conf/$node; fi
		scp_from_w $node $path $OUTDIR/conf/$node 1> /dev/null &
	fi
done
wait
}

for i in $ALL_NODES; do
	ssh_w $i "rm -rf $WORKER_TMP_DIR/*" > /dev/null
done


#Run Data Collection Scripts
trap 'on_exit; exit' SIGINT SIGKILL SIGTERM
$MASTER_SCRIPT_DIR/runinstruments $OUTDIR/jobhistory


getJobid
get_instruments &
get_conf &

wait
rm -rf $MASTER_RESULTS_DIR/$JOBID
mv $OUTDIR $MASTER_RESULTS_DIR/$JOBID

echo ****DONE!****
echo output located at $MASTER_RESULTS_DIR/$JOBID
